/* Generated by Nim Compiler v0.10.1 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/mason/Software/nim/lib -o .nimcache/stdlib_times.o .nimcache/stdlib_times.c */
#define NIM_INTBITS 64
#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void) {
}

