/* Generated by Nim Compiler v0.10.1 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/mason/Software/nim/lib -o .nimcache/stdlib_os.o .nimcache/stdlib_os.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TY118608 TY118608;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY118608 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
NIM_BOOL envcomputed_118607;
TY118608* environment_118609;
extern NCSTRING* environ;
extern int cmdCount;
extern NCSTRING* cmdLine;
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit)(void) {
}

